version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: order-cost-calculator-backend:latest
    container_name: backend
    ports:
      - "8082:8082"
    volumes:
      - ./docker-data:/app/data
      - ./logs:/app/logs
      - ./backend/application-docker.properties:/app/application.properties
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/procostdb_new;AUTO_SERVER=TRUE
      - SPRING_SQL_INIT_MODE=never
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: order-cost-calculator-frontend:latest
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://localhost:8082
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  docker-data:
  logs:

networks:
  app-network:
    driver: bridge
