apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-cost-calculator-data
  namespace: order-cost-calculator
  labels:
    app: order-cost-calculator
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Change this based on your cluster's storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-cost-calculator-logs
  namespace: order-cost-calculator
  labels:
    app: order-cost-calculator
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
